import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { useState } from "react";
import { useIsMobile } from "../hooks/useIsMobile";
import zojeLogo from "../assets/zoje_logo.png";
export default function CustomerLayout() {
    const navigate = useNavigate();
    const isMobile = useIsMobile(768);
    const [menuOpen, setMenuOpen] = useState(false);
    return (_jsxs("div", { className: "customer-layout", children: [_jsxs("header", { className: "support-header", children: [_jsxs("div", { className: "header-logo", onClick: () => navigate("/dashboard"), children: [_jsx("img", { src: zojeLogo, alt: "Zoje Machineries", className: "logo-image" }), !isMobile && (_jsxs("div", { className: "logo-text", children: [_jsx("div", { className: "logo-title", children: "Zoje Machineries Support" }), _jsx("div", { className: "logo-subtitle", children: "After-Sales Service Portal \u2014 Bangladesh" })] }))] }), isMobile ? (_jsx("button", { onClick: () => setMenuOpen(!menuOpen), className: `mobile-menu-button ${menuOpen ? "active" : ""}`, children: "\u2630" })) : (_jsxs("div", { className: "header-nav-wrapper", children: [_jsxs("nav", { className: "desktop-nav", children: [_jsxs(NavLink, { to: "/dashboard", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83D\uDCCA" }), "Dashboard"] }), _jsxs(NavLink, { to: "/machines/registered", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83C\uDFED" }), "My Machines"] }), _jsxs(NavLink, { to: "/tickets/history", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83C\uDFAB" }), "Tickets"] }), _jsxs(NavLink, { to: "/contact", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83D\uDCDE" }), "Contact"] }), _jsxs(NavLink, { to: "/profile", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83D\uDC64" }), "Profile"] }), _jsxs(NavLink, { to: "/ai/assistant", className: ({ isActive }) => `nav-link ${isActive ? "active" : ""}`, children: [_jsx("span", { className: "nav-icon", children: "\uD83E\uDD16" }), "Quick Help"] })] }), _jsx("button", { onClick: () => navigate("/tech/dashboard"), className: "secondary-button", children: "Technician Mode" })] }))] }), isMobile && (_jsxs("div", { className: `mobile-menu-drawer ${menuOpen ? "open" : ""}`, children: [_jsx(MobileNavItem, { to: "/dashboard", label: "Dashboard", onClick: () => setMenuOpen(false) }), _jsx(MobileNavItem, { to: "/machines/registered", label: "View My Machines", onClick: () => setMenuOpen(false) }), _jsx(MobileNavItem, { to: "/tickets/history", label: "My Support Tickets", onClick: () => setMenuOpen(false) }), _jsx(MobileNavItem, { to: "/contact", label: "Contact Support", onClick: () => setMenuOpen(false) }), _jsx(MobileNavItem, { to: "/profile", label: "Profile & Company Info", onClick: () => setMenuOpen(false) }), _jsx("div", { className: "mobile-menu-footer", children: _jsx("button", { onClick: () => {
                                setMenuOpen(false);
                                navigate("/tech/dashboard");
                            }, className: "primary-button", style: { width: "100%" }, children: "Technician Mode" }) })] })), _jsx("main", { className: "main-content", children: _jsx(Outlet, {}) })] }));
}
function MobileNavItem({ to, label, onClick }) {
    return (_jsx(NavLink, { to: to, onClick: onClick, className: ({ isActive }) => `mobile-nav-item ${isActive ? "active" : ""}`, children: label }));
}
//# sourceMappingURL=CustomerLayout.js.map